### ISSUE TITLE
Cypress - cy.visit() failed trying to load. > Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by dashqa** [mmisty/cypress-allure-adapter#79]
Hi @mmisty, in our project, we use the Nx build system and want to use your cypress-allure-adapter for component and end-to-end tests. There are no issues with component tests when using the adapter. We specify the build target for Nx, which is our main application build, I suspect that Nx independently locates the webpack configuration from the build target we specified and passes it to Cypress.
Our problem arises with end-to-end tests. Once we apply the `configureAllureAdapterPlugins` plugin, Cypress no longer recognizes the host where the application is deployed. All tests containing cy.visit() on the local host address fail with an error:

```
CypressError: `cy.visit()` failed trying to load:
http://localhost:4200/
We attempted to make an http request to this URL but the request failed without a response.
We received this error at the network level:
  > Error: connect ECONNREFUSED 127.0.0.1:4200
Common situations why this would fail:
  - you don't have internet access
  - you forgot to run / boot your web server
  - your web server isn't accessible
  - you have weird network configuration settings on your computer
      at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:147833:82)
      at visitFailedByErr (http://localhost:4200/__cypress/runner/cypress_runner.js:147225:12)
      at <unknown> (http://localhost:4200/__cypress/runner/cypress_runner.js:147832:11)
      at tryCatcher (http://localhost:4200/__cypress/runner/cypress_runner.js:18744:23)
      at Promise._settlePromiseFromHandler (http://localhost:4200/__cypress/runner/cypress_runner.js:16679:31)
      at Promise._settlePromise (http://localhost:4200/__cypress/runner/cypress_runner.js:16736:18)
      at Promise._settlePromise0 (http://localhost:4200/__cypress/runner/cypress_runner.js:16781:10)
      at Promise._settlePromises (http://localhost:4200/__cypress/runner/cypress_runner.js:16857:18)
      at _drainQueueStep (http://localhost:4200/__cypress/runner/cypress_runner.js:13451:12)
      at _drainQueue (http://localhost:4200/__cypress/runner/cypress_runner.js:13444:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:13460:5)
      at Async.drainQueues (http://localhost:4200/__cypress/runner/cypress_runner.js:13330:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/e2e/app.e2e.ts:8:0)
  
  From Node.js Internals:
    Error: connect ECONNREFUSED 127.0.0.1:4200
        at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
    From previous event:
        at q._onResolveUrl (<embedded>:4626:6886)
        at <unknown> (<embedded>:4626:31631)
    From previous event:
        at p.<anonymous> (<embedded>:4626:31523)
        at p.emit (node:events:527:28)
        at p.emitUntyped (<embedded>:4337:84346)
        at <unknown> (<embedded>:4337:91863)
        at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
```

Also debugging:
```
// cy.visit('/'):

cypress:server:request exhausted all attempts retrying request { auth: null, failOnStatusCode: true, retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, retryIntervals: [ 0, 100, 200, 200 ], method: 'GET', body: null, headers: { accept: 'text/html,*/*', 'Accept-Encoding': 'gzip, deflate', 'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36' }, timeout: 30000, isFromSpecBridge: false, hasAlreadyVisitedUrl: false, gzip: false, url: 'http://localhost:4200/', onBeforeReqInit: [Function: C], followAllRedirects: true, requestId: 'request31', delaysRemaining: [], err: Error: connect ECONNREFUSED 127.0.0.1:4200     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 4200 } } +0ms

// fetching fonts:

cypress:server:request received an error making http request { browserPreRequest: { requestId: '44905.8', method: 'GET', url: 'http://localhost:4200/__/fonts/FiraCode-VF.woff2', headers: { 'sec-ch-ua': '"Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"', Referer: 'http://localhost:4200/__/assets/index-fdbb1606.css', Origin: 'http://localhost:4200', 'sec-ch-ua-mobile': '?0', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36', 'sec-ch-ua-platform': '"macOS"' }, resourceType: 'font', originalResourceType: 'Font' }, timeout: undefined, retryIntervals: [], url: 'http://localhost:4200/__/fonts/FiraCode-VF.woff2', time: false, requestId: 'request6', retryOnNetworkFailure: true, retryOnStatusCodeFailure: false, delaysRemaining: [], err: Error: connect ECONNREFUSED 127.0.0.1:4200     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) { errno: -61, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 4200 } } +2s
```
I am confident that webpack-dev-server is actively listening on this port, as I was able to manually open it in the browser.
![1_1-2](https://github.com/mmisty/cypress-allure-adapter/assets/1376668/a0271ac7-082d-488c-8e2f-e1e2c1d27aa3)

Examples:
```TypeScript
// ERROR
describe('app', () => {
  it('should load page successfully', () => {
    cy.visit('/');
    cy.get('body').should('exist');
  });
});

// PASSED
describe('app', () => {
  it('should load page successfully', () => {
    cy.visit('https://google.com');
    cy.get('body').should('exist');
  });
});
```

Cypress config:
```TypeScript
import { join, resolve } from 'path';
import { nxE2EPreset } from '@nx/cypress/plugins/cypress-preset';
import { nxComponentTestingPreset } from '@nx/react/plugins/component-testing';
import { defineConfig as _defineConfig } from 'cypress';
import { configureAllureAdapterPlugins } from '@mmisty/cypress-allure-adapter/plugins';
import { joinPathFragments } from '@nx/devkit';

const { beforeRunHook } = require('cypress-mochawesome-reporter/lib');

const retries = {
  runMode: process.env.CY_RETRY ? parseInt(process.env.CY_RETRY, 10) : 0,
  openMode: 2,
};

const issuePrefix = process.env.JIRA_ISSUE_PREFIX;

const rootDir = resolve(__dirname, '../../../../../');
const reportDir = join(rootDir, 'reports/cypress');

export const defineConfig = (
  dirname: string, // project's absolute directory path
  projectDir: string, // project's relative directory path
  testType: 'component' | 'e2e' = 'component'
): Cypress.ConfigOptions => {
  const commonOptions = {
    retries,
    reporter: join(rootDir, 'node_modules/cypress-mochawesome-reporter'),
    video: false,
    reporterOptions: {
      reportDir: joinPathFragments(reportDir, projectDir),
      charts: true,
      quiet: true,
      embeddedScreenshots: true,
      inlineAssets: true,
      videoOnFailOnly: true,
      saveAllAttempts: false,
      overwrite: true,
      saveHtml: true,
      saveJson: true,
      showPending: true,
      showSkipped: true,
      showHooks: 'always',
      reportFilename: 'results_[status]-[datetime]',
      timestamp: 'isoDateTime',
    },
    videosFolder: joinPathFragments(reportDir, projectDir, 'videos'),
    screenshotsFolder: joinPathFragments(reportDir, projectDir, 'screenshots'),
    viewportHeight: 660,
    viewportWidth: 1000,
    numTestsKeptInMemory: 400,
    env: {
      allure: true,
      allureAttachRequests: true,
      allureResults: join(rootDir, 'reports/allure/results'),
      allureResultsWatchPath: join(rootDir, 'reports/allure/results'),
      allureReuseAfterSpec: true,
      allureShowDuplicateWarn: true,
      allureSkipSteps: `"after each" hook*,"after all" hook*,"before all" hook*`,
      issuePrefix,
      tsConfig: join(dirname, 'cypress/tsconfig.json'),
    },
  };

  if (testType === 'e2e') {
    return _defineConfig({
      e2e: {
        ...nxE2EPreset(dirname, {
          bundler: 'webpack',
        }),
        experimentalRunAllSpecs: true,
        supportFile: join(dirname, 'cypress/support/e2e.ts'),
        specPattern: join(dirname, 'cypress/**/**.e2e.{js,jsx,ts,tsx}'),
        setupNodeEvents(
          on: Cypress.PluginEvents,
          config: Cypress.PluginConfigOptions
        ) {
          configureAllureAdapterPlugins(on, config);
          // require('cypress-mochawesome-reporter/plugin')(on);
          // require('@cypress/code-coverage/task')(on, config);

          // const allure = configureAllureAdapterPlugins(on, config);
          // on('before:run', async (details) => {
          //   allure?.writeEnvironmentInfo({
          //     info: {
          //       os: details.system.osName,
          //       osVersion: details.system.osVersion,
          //       browser: `${details.browser?.displayName} ${details.browser?.version}`,
          //     },
          //   });
          //   await beforeRunHook(details);
          // });
          return config;
        },
        ...commonOptions,
      },
    });
  }

  return _defineConfig({
    component: {
      ...nxComponentTestingPreset(dirname, {
        bundler: 'webpack',
      }),
      supportFile: join(dirname, 'cypress/support/component.ts'),
      specPattern: join(dirname, '**/*.ct.{js,jsx,ts,tsx}'),
      indexHtmlFile: join(__dirname, 'support/component-index.html'),
      setupNodeEvents(
        on: Cypress.PluginEvents,
        config: Cypress.PluginConfigOptions
      ) {
        require('cypress-mochawesome-reporter/plugin')(on);
        require('@cypress/code-coverage/task')(on, config);
        on('file:preprocessor', require('@cypress/code-coverage/use-babelrc'));

        const allure = configureAllureAdapterPlugins(on, config);
        on('before:run', async (details) => {
          allure?.writeEnvironmentInfo({
            info: {
              os: details.system.osName,
              osVersion: details.system.osVersion,
              browser: `${details.browser?.displayName} ${details.browser?.version}`,
            },
          });
          await beforeRunHook(details);
        });
        return config;
      },
      ...commonOptions,
    },
  });
};
```

Node: v18.16.1
Cypress package version: 12.17.3
Cypress binary version: 12.17.3
Electron version: 21.0.0
Bundled Node version: 16.16.0
nx: 17.0.2
@mmisty/cypress-allure-adapter: 0.15.2

**Comment by dashqa** [comment]
found out it was Node v18 issue.
this helped me - https://github.com/cypress-io/cypress/issues/25528#issuecomment-1400088144
